---
title: "Respuestas a la tarea 4"
summary: ""
weight: 1
type: book
toc: false
---



<div id="pregunta-1" class="section level2">
<h2>Pregunta 1</h2>
<p>El archivo <em>basque.csv</em> contiene los datos empleados por Abadie y Gardeazabal (2003) para estimar el efecto del terrorismo en el PIB per cápita (<strong>gdpcap</strong>) en el País Vasco usando el método de control sintético. Los autores consideran como periodo pre intervención a 1955 - 1969.</p>
<ol style="list-style-type: lower-alpha">
<li><p>[25 puntos] Estime el control sintético del PIB per cápita del País Vasco usando como <em>grupo donador</em> al resto de las regiones de España. Esto es, encuentre la matriz <span class="math inline">\(W\)</span> que otorga pesos a las distintas regiones usando una serie de predictores observables. Para este propósito, use como predictores el promedio de las siguientes variables para el periodo 1964-1969:</p>
<ul>
<li>La inversión como porcentaje del PIB, <strong>invest</strong></li>
<li>El porcentaje de la población analfabeta, <strong>school.illit</strong></li>
<li>El porcentaje de la población con educación primaria, <strong>school.prim</strong></li>
<li>El porcentaje de la población con educación media, <strong>school.med</strong></li>
<li>El porcentaje de la población con educación superior, <strong>school.high</strong></li>
<li>El porcentaje de la población con educación más que superior, <strong>school.post.high</strong></li>
</ul>
<p>Además, use como <em>predictores especiales</em> los siguientes valores:</p>
<ul>
<li>El promedio del PIB per capita, <strong>gdpcap</strong>, de 1960 a 1969</li>
<li>La densidad de población, <strong>popdens</strong>, de 1969</li>
<li>El promedio de la participación de la agricultura, <strong>sec.agriculture</strong>, de 1961 a 1969</li>
<li>El promedio de la participación de la energía, <strong>sec.energy</strong>, de 1961 a 1969</li>
<li>El promedio de la participación de la industria, <strong>sec.industry</strong>, de 1961 a 1969</li>
<li>El promedio de la participación de la construcción, <strong>sec.construction</strong>, de 1961 a 1969</li>
<li>El promedio de la participación de los servicios, <strong>sec.services.venta</strong>, de 1961 a 1969</li>
<li>El promedio de la participación de los servicios no comerciables, <strong>sec.services.nonventa</strong>, de 1961 a 1969</li>
</ul>
<p>Note que el País Vasco está identificado con el número 17 de la variable <strong>regionno</strong>. Realice el procedimiento de optimización para minimizar las discrepancias entre la unidad tratada y su sintético usando el periodo 1960-1969.</p>
<p>¿Qué regiones y con qué pesos contribuyen a construir el País Vasco sintético?</p>
<p><em>Implementamos el método de control sintético:</em></p>
<p><em>Recuperamos los pesos:</em></p>
<pre class="r"><code>print(synth.tables$tab.w)</code></pre>
<pre><code>##    w.weights                   unit.names unit.numbers
## 2      0.000                    Andalucia            2
## 3      0.000                       Aragon            3
## 4      0.000       Principado De Asturias            4
## 5      0.000             Baleares (Islas)            5
## 6      0.000                     Canarias            6
## 7      0.000                    Cantabria            7
## 8      0.000              Castilla Y Leon            8
## 9      0.000           Castilla-La Mancha            9
## 10     0.851                     Cataluna           10
## 11     0.000         Comunidad Valenciana           11
## 12     0.000                  Extremadura           12
## 13     0.000                      Galicia           13
## 14     0.149        Madrid (Comunidad De)           14
## 15     0.000           Murcia (Region de)           15
## 16     0.000 Navarra (Comunidad Foral De)           16
## 18     0.000                   Rioja (La)           18</code></pre>
<p><em>El País Vasco sintético se obtiene como una combinación de Cataluña y Madrid, con unos pesos de 0.851 y 0.149, respectivamente.</em></p></li>
<li><p>[25 puntos] Obtenga un gráfico en donde represente las series de tiempo del PIB per cápita del País Vasco que efectivamente se realizó, la de su correspondiente control sintético y la del promedio simple del resto de las regiones españolas.</p>
<p><em>Recuperamos las series originales y sintética del País Vasco:</em></p>
<pre class="r"><code>Ys &lt;- dataprep.out$Y0plot %*% synth.out$solution.w

Y1 &lt;- dataprep.out$Y1plot</code></pre>
<p>*Por otro lado, podemos calcular el promedio sobre todas las regiones de la matriz <span class="math inline">\(Y0plot\)</span>:</p>
<pre class="r"><code>Y0media &lt;- matrix(rowMeans(dataprep.out$Y0plot))</code></pre>
<p><em>Y ponemos todo en un data frame para graficarlo fácilmente:</em></p>
<pre class="r"><code>data.plot &lt;- as.data.frame(cbind(Y1,Ys, Y0media))

colnames(data.plot) &lt;- c(&quot;Y1&quot;,&quot;Ys&quot;,&quot;Y0media&quot;)
data.plot &lt;- data.plot %&gt;% 
  mutate(year=seq(from=1955, to=1997))

#Gráfico de series
data.plot %&gt;% 
  ggplot(aes(x=year))+
  geom_line(aes(y=Y1, linetype = &quot;País Vasco&quot;)) +
  geom_line(aes(y=Ys, linetype = &quot;Sintético&quot;))+
  geom_line(aes(y=Y0media, linetype = &quot;Resto de España&quot;))+
  geom_vline(xintercept=1970, color = &quot;black&quot;, size=1, linetype=&quot;dashed&quot;)+
  scale_x_continuous(breaks=seq(1955, 1997, 5))+
   labs(x = &quot;Año&quot;,
    y = &quot;PIB per capita&quot;,
    linetype = &quot;Legend&quot;) +
  scale_linetype_manual(values = c(&quot;País Vasco&quot;=&quot;solid&quot;, &quot;Sintético&quot;=&quot;dashed&quot;, &quot;Resto de España&quot;=&quot;dotted&quot;))</code></pre>
<p><img src="/tareas/tarea_4/tarea_4_respuestas_files/figure-html/unnamed-chunk-5-1.png" width="672" />
<em>El País Vasco era más rico que el promedio del resto de las regiones españolas. Durante el periodo post al inicio de la actividad terrorista, el resto de España siguió creciendo, pero el País Vasco se acercó hacia abajo.</em></p></li>
<li><p>[25 puntos] Genere una gráfica de brechas que muestre el efecto del terrorismo sobre el PIB per cápita. La brecha es la diferencia entre la serie de tiempo realizada y su contraparte sintética.</p>
<p><em>El gráfico de brechas se obtiene fácilmente con las funciones de Synth:</em></p>
<pre class="r"><code>gaps.plot(synth.res = synth.out,
      dataprep.res = dataprep.out,
      tr.intake = 1970,
      Ylab = c(&quot;GDP per capita&quot;),
      Xlab = c(&quot;year&quot;), 
      Ylim = c(-4,4))</code></pre>
<p><img src="/tareas/tarea_4/tarea_4_respuestas_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p><em>El gráfico de las trayectorias es:</em></p>
<p><img src="/tareas/tarea_4/tarea_4_respuestas_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p></li>
<li><p>[25 puntos] Realice un ejercicio de placebos en el espacio, similar al que llevamos a cabo en el laboratorio. La idea es estimar el control sintético para todas las regiones. Una vez que tenga el PIB per capita sintético para las 17 regiones, genere un histograma donde represente la razón del error de predicción cuadrado medio. Para ello, para cada región, debe obtener el error de predicción cuadrado promedio para los periodos pre y post intervención y luego obtener la razón de estos. ¿Cómo es la razón del error de predicción cuadrado medio para el País Vasco y qué nos dice de la significancia estadística del efecto estimado?</p>
<p><em>Noten que la región 1 es el total de España. No queremos usar esa región, así que el loop debe ignorarla. El ejercicio placebo es:</em></p>
<pre class="r"><code>placebos &lt;- data.frame(matrix(ncol = 17, nrow = 43))

#Hacemos un ciclo para operacionalizar el trabajo
for (j in 2:18) {

tunit &lt;- j
tunit_m1 &lt;- j-1
tunit_p1 &lt;- j+1

if (j==2)
  dpool &lt;- c(3:18)
else
  if (j==18)
dpool &lt;- c(2:17)
  else
dpool &lt;- c(2:tunit_m1,tunit_p1:18)

dataprep.out &lt;- dataprep(foo = data_vasco,
                  predictors = c(&quot;invest&quot;, &quot;school.illit&quot;, &quot;school.prim&quot;, &quot;school.med&quot;, &quot;school.high&quot;, &quot;school.post.high&quot;),
                  predictors.op = c(&quot;mean&quot;),
                  dependent = c(&quot;gdpcap&quot;),
                  unit.variable = c(&quot;regionno&quot;),
                  time.variable = c(&quot;year&quot;),
                  special.predictors = list(
                    list(&quot;gdpcap&quot;, 1960:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.agriculture&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.energy&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.industry&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.construction&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.services.venta&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.services.nonventa&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;popdens&quot;, 1969,c(&quot;mean&quot;))),
                  treatment.identifier = j,
                  controls.identifier = dpool,
                  time.predictors.prior = c(1964:1969),
                  time.optimize.ssr = c(1960:1969),
                  unit.names.variable = c(&quot;regionname&quot;),
                  time.plot = c(1955:1997))

#Repetimos tareas
synth.out &lt;- synth(data.prep.obj = dataprep.out)
Ys &lt;- dataprep.out$Y0plot %*% synth.out$solution.w
Y1 &lt;- dataprep.out$Y1plot

data.plot &lt;- as.data.frame(cbind(Y1,Ys))
colnames(data.plot) &lt;- c(&quot;Y1&quot;,&quot;Ys&quot;)
data.plot &lt;- data.plot %&gt;% 
  mutate(gap=Y1-Ys)

#Guardamos donde corresponde
placebos[,j-1] &lt;- data.plot$gap

#Para ir viendo en dónde vamos
print(j)

}


##Ahora tenemos un panel de regiones placebo
placebos &lt;- placebos %&gt;% 
  mutate(year=seq(from=1955, to=1997))

#Pasamos todo a formato long
placebos &lt;- placebos %&gt;%
  pivot_longer(cols=starts_with(&quot;X&quot;),
           names_to = &quot;region&quot;,
           values_to = &quot;gdp_synth&quot;) %&gt;% 
  mutate(region=as.numeric(substr(region,2,3))) %&gt;% 
  mutate(region=region+1) %&gt;% 
  mutate(treated=ifelse(region==17,1,0)) %&gt;% 
  mutate(treated=factor(treated, levels=c(&quot;0&quot;,&quot;1&quot;), labels=c(&quot;regiones de control&quot;, &quot;País Vasco&quot;)))</code></pre>
<p><em>No era necesario replicar este gráfico, pero lo hacemos para visualizar qué esperar:</em></p>
<pre class="r"><code>placebos %&gt;%
  ggplot(aes(x=year, y=gdp_synth, group=region, linetype=treated, color=treated))+
  geom_line()+
  scale_linetype_manual(values=c(&quot;solid&quot;, &quot;solid&quot;))+
  scale_color_manual(values=c(&quot;grey&quot;,&quot;black&quot;)) +
  ylab(&quot;PIB per cápita&quot;)+
  xlab(&quot;Año&quot;)+
  geom_vline(xintercept=1970, color = &quot;black&quot;, size=.5, linetype=&quot;dashed&quot;)+
  geom_hline(yintercept=0, color = &quot;black&quot;, size=.5, linetype=&quot;dashed&quot;)+
  scale_x_continuous(breaks=seq(1955, 1997, 5))+
  theme(legend.title = element_blank(),
    legend.position = c(.14, .90),
    legend.box.background = element_rect(color=&quot;black&quot;, size=.3),
    legend.box.margin = margin(1, 1, 1, 1))</code></pre>
<p><img src="/tareas/tarea_4/tarea_4_respuestas_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p><em>La mayoría de las regiones tienen buen ajuste pre intervención y la brecha post intervención del País Vasco efectivamente parece atípica. Calculemos el error cuadrático de predicción promedio pre y post intervención:</em></p>
<pre class="r"><code>mspe &lt;- placebos %&gt;% 
  mutate(pre = ifelse(year&lt;1970,&quot;pre&quot;,&quot;post&quot;),
         spe = gdp_synth^2) %&gt;% 
  group_by(region, pre) %&gt;% 
  summarise(mspe = mean(spe)) %&gt;% 
  ungroup() %&gt;%
  pivot_wider(id_cols = region,
              names_from = pre,
              values_from = mspe) %&gt;%
  mutate(ratio_mspe=post/pre) %&gt;% 
  mutate(tipo = ifelse(region==17, &quot;País Vasco&quot;, &quot;Otras regiones&quot;))</code></pre>
<p><em>Y hago un histograma:</em></p>
<pre class="r"><code>mspe %&gt;% 
  ggplot(aes(ratio_mspe, fill=tipo)) +
  geom_histogram(binwidth  = 20)</code></pre>
<p><img src="/tareas/tarea_4/tarea_4_respuestas_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p><em>El País Vasco resulta tener la sexta razón de MSPE más grande. A continuación vemos un resumen de los datos usados para obtener el MSPE. Para que esta razón sea grande, puede ser que el numerador sea grande (es decir, que las diferencias post entre las series observadas y las sintéticas sean grandes), o que el denominador sea pequeño (es decir, que las diferencias pre sean pequeñas). La diferencia post del País Vasco es de hecho la segunda más grande, solo después de región 4, Asturias. Las otras regiones que tienen MSPE más altos que el País Vasco tienen diferencias post muy pequeñas, pero que se ven infladas por muy buenos ajustes pre. En general, la evidencia parece indicar que efectivamente el efecto sobre el País Vasco es atípico.</em></p>
<pre class="r"><code>mspe %&gt;% 
  arrange(desc(ratio_mspe))</code></pre>
<pre><code>## # A tibble: 17 × 5
##    region    post      pre ratio_mspe tipo          
##     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;         
##  1      4 0.711   0.000628    1132.   Otras regiones
##  2      2 0.338   0.000748     452.   Otras regiones
##  3     16 0.0861  0.000357     241.   Otras regiones
##  4     11 0.138   0.00185       74.5  Otras regiones
##  5      7 0.0898  0.00144       62.2  Otras regiones
##  6     17 0.493   0.00821       60.1  País Vasco    
##  7     18 0.0395  0.000658      60.0  Otras regiones
##  8     10 0.471   0.00848       55.5  Otras regiones
##  9     13 0.0674  0.00181       37.3  Otras regiones
## 10      3 0.0614  0.00190       32.3  Otras regiones
## 11      9 0.165   0.00548       30.0  Otras regiones
## 12      5 4.09    0.152         26.9  Otras regiones
## 13     15 0.175   0.00846       20.7  Otras regiones
## 14      6 0.0733  0.00725       10.1  Otras regiones
## 15     12 0.741   0.0790         9.37 Otras regiones
## 16      8 0.00724 0.000933       7.75 Otras regiones
## 17     14 0.674   0.593          1.14 Otras regiones</code></pre></li>
</ol>
</div>
