---
title: "Métodos de emparejamiento en R"
summary: " "
weight: 1
type: book
toc: false
---

<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />


<p><a href="/notas/cattaneo_smoking.csv">cattaneo_smoking.csv</a></p>
<p><a href="/notas/lab_psm.R">lab_psm.R</a></p>
<div id="paquetes" class="section level2">
<h2>Paquetes</h2>
<p>Usaremos dos paquetes nuevos: <em>MatchIt</em> y <em>cobalt</em>, que pueden descargar como cualquier otro paquete desde CRAN.</p>
</div>
<div id="datos-no-experimentales-de-una-muestra-de-mujeres" class="section level2">
<h2>Datos no experimentales de una muestra de mujeres</h2>
<p>Los datos en <em>cattaneo_smoking.csv</em> (Cattaneo, 2010) son de una muestra de mujeres que incluye un indicador de si la madre fumó durante el embarazo. El propósito es evaluar el efecto de fumar sobre el peso de los bebés al nacer. Se incluyen una serie de covariables que usaremos para modelar el <em>propensity score</em>.</p>
</div>
<div id="matchit-para-realizar-los-emparejamientos" class="section level2">
<h2><em>matchit</em> para realizar los emparejamientos</h2>
<p>La función que usaremos para hacer los emparejamientos es <em>matchit</em> de la librería <em>MatchIt</em>. Antes de hacer los emparejamientos, construimos la dummy de tratamiento, <strong>smoke</strong>, una dummy para mujeres casadas, <strong>married</strong>, y una dummy para si el caso en cuestión es el primer bebé. <strong>firstbaby</strong>:</p>
<pre class="r"><code>data.smoking&lt;-read_csv(
  &quot;./cattaneo_smoking.csv&quot;,
  locale = locale(encoding = &quot;latin1&quot;)) %&gt;% 
  clean_names() %&gt;% 
  mutate(smoke=ifelse(mbsmoke==&quot;smoker&quot;,1,0)) %&gt;% 
  mutate(married=ifelse(mmarried==&quot;married&quot;,1,0)) %&gt;% 
  mutate(firstbaby=ifelse(fbaby==&quot;Yes&quot;,1,0))

#Asegurarse que no hay NA, matchit no acepta NA
data.smoking &lt;- data.smoking[complete.cases(data.smoking), ]

#Una semilla para todo el trabajo
set.seed(1021)</code></pre>
<p>Notemos que, si solo comparamos a las mujeres que fuman con las que no fuman, estamos comparando personas muy diferentes:</p>
<pre class="r"><code>datasummary_balance(~smoke,
                    fmt = &quot;%.2f&quot;,
                    data = select(data.smoking, smoke, married, firstbaby, medu, nprenatal, foreign, mhisp, fage),
                    dinm_statistic = &quot;p.value&quot;,
                    title = &quot;Pruebas de balance&quot;,
                    notes = &quot;Fuente: Cattaneo (2009)&quot;)</code></pre>
<table style="NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;" class="table">
<caption>
<span id="tab:unnamed-chunk-2">Table 1: </span>Pruebas de balance
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
0
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
1
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
</tr>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
Std. Dev.
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
Std. Dev.
</th>
<th style="text-align:right;">
Diff. in Means
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
married
</td>
<td style="text-align:right;">
0.75
</td>
<td style="text-align:right;">
0.43
</td>
<td style="text-align:right;">
0.47
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:right;">
-0.28
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
firstbaby
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:right;">
0.37
</td>
<td style="text-align:right;">
0.48
</td>
<td style="text-align:right;">
-0.08
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
medu
</td>
<td style="text-align:right;">
12.93
</td>
<td style="text-align:right;">
2.53
</td>
<td style="text-align:right;">
11.64
</td>
<td style="text-align:right;">
2.17
</td>
<td style="text-align:right;">
-1.29
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
nprenatal
</td>
<td style="text-align:right;">
10.96
</td>
<td style="text-align:right;">
3.52
</td>
<td style="text-align:right;">
9.86
</td>
<td style="text-align:right;">
4.21
</td>
<td style="text-align:right;">
-1.10
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
foreign
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:right;">
0.24
</td>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
0.16
</td>
<td style="text-align:right;">
-0.03
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
mhisp
</td>
<td style="text-align:right;">
0.04
</td>
<td style="text-align:right;">
0.19
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
0.15
</td>
<td style="text-align:right;">
-0.01
</td>
<td style="text-align:right;">
0.05
</td>
</tr>
<tr>
<td style="text-align:left;">
fage
</td>
<td style="text-align:right;">
27.84
</td>
<td style="text-align:right;">
8.79
</td>
<td style="text-align:right;">
24.74
</td>
<td style="text-align:right;">
11.15
</td>
<td style="text-align:right;">
-3.10
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Fuente: Cattaneo (2009)
</td>
</tr>
</tfoot>
</table>
</div>
<div id="estimación-del-ps" class="section level2">
<h2>Estimación del PS</h2>
<p>Una manera de hacer más eficiente el uso de las <em>fórmulas</em> es usando <em>as.formula</em>:</p>
<pre class="r"><code>binaria &lt;- &quot;smoke&quot;
variables &lt;- c(&quot;married&quot;, &quot;firstbaby&quot;, &quot;medu&quot;, &quot;nprenatal&quot;, &quot;foreign&quot;, &quot;mhisp&quot;, &quot;fage&quot;)

ps &lt;- as.formula(paste(binaria,
                         paste(variables,
                               collapse =&quot;+&quot;),
                         sep= &quot; ~ &quot;))
print(ps)</code></pre>
<pre><code>## smoke ~ married + firstbaby + medu + nprenatal + foreign + mhisp + 
##     fage</code></pre>
<p>Usamos <em>matchit</em> para estimar el PS y realizar los emparejamientos con el algoritmo que indiquemos:</p>
<pre class="r"><code>m.out &lt;- matchit(formula=ps,
                 method = &quot;nearest&quot;,
                 ratio = 1,
                 distance= &quot;logit&quot;,
                 replace = FALSE,
                 data = data.smoking)</code></pre>
<p>El resumen del procedimiento da bastante información sobre el pareamiento:</p>
<pre class="r"><code>summary(m.out)</code></pre>
<pre><code>## 
## Call:
## matchit(formula = ps, data = data.smoking, method = &quot;nearest&quot;, 
##     distance = &quot;logit&quot;, replace = FALSE, ratio = 1)
## 
## Summary of Balance for All Data:
##           Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
## distance         0.2568        0.1700          0.6673     1.4475    0.2002
## married          0.4734        0.7515         -0.5569          .    0.2781
## firstbaby        0.3715        0.4531         -0.1689          .    0.0816
## medu            11.6389       12.9299         -0.5955     0.7316    0.0717
## nprenatal        9.8623       10.9629         -0.2616     1.4301    0.0376
## foreign          0.0255        0.0598         -0.2181          .    0.0344
## mhisp            0.0243        0.0363         -0.0776          .    0.0120
## fage            24.7431       27.8444         -0.2782     1.6070    0.0468
##           eCDF Max
## distance    0.3329
## married     0.2781
## firstbaby   0.0816
## medu        0.2549
## nprenatal   0.1259
## foreign     0.0344
## mhisp       0.0120
## fage        0.1377
## 
## 
## Summary of Balance for Matched Data:
##           Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
## distance         0.2568        0.2564          0.0033     1.0110    0.0005
## married          0.4734        0.4769         -0.0070          .    0.0035
## firstbaby        0.3715        0.3981         -0.0551          .    0.0266
## medu            11.6389       11.6019          0.0171     0.7064    0.0161
## nprenatal        9.8623        9.8588          0.0008     1.1543    0.0059
## foreign          0.0255        0.0174          0.0514          .    0.0081
## mhisp            0.0243        0.0231          0.0075          .    0.0012
## fage            24.7431       24.5799          0.0146     1.0787    0.0124
##           eCDF Max Std. Pair Dist.
## distance    0.0093          0.0046
## married     0.0035          0.2202
## firstbaby   0.0266          0.4575
## medu        0.0417          0.5168
## nprenatal   0.0185          0.7039
## foreign     0.0081          0.2425
## mhisp       0.0012          0.2781
## fage        0.0556          0.6457
## 
## Sample Sizes:
##           Control Treated
## All          3778     864
## Matched       864     864
## Unmatched    2914       0
## Discarded       0       0</code></pre>
</div>
<div id="verificación-del-balance" class="section level2">
<h2>Verificación del balance</h2>
<p>Gráfico de nube:</p>
<pre class="r"><code>plot(m.out, type = &quot;jitter&quot;)</code></pre>
<p><img src="/notas/emparejamiento_en_R_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre><code>## [1] &quot;To identify the units, use first mouse button; to stop, use second.&quot;</code></pre>
<pre><code>## integer(0)</code></pre>
<p>Histograma:</p>
<pre class="r"><code>plot(m.out, type = &quot;hist&quot;)</code></pre>
<p><img src="/notas/emparejamiento_en_R_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Podemos guardar un objeto con la muestra emparejada usando <em>match.data</em> y observar quién hace match con quién:</p>
<pre class="r"><code>m.data &lt;- match.data(m.out)

head(m.out$match.matrix)</code></pre>
<pre><code>##    [,1]  
## 11 &quot;4130&quot;
## 20 &quot;2234&quot;
## 25 &quot;1740&quot;
## 43 &quot;2857&quot;
## 47 &quot;305&quot; 
## 49 &quot;1442&quot;</code></pre>
<p>Una propuesta para determinar si el emparejamiento fue exitoso es observar las diferencias promedio estandarizadas (SMD) entre los grupos tratados y no tratados, antes y después del emparejamiento.</p>
<p><span class="math display">\[SMD_X=\frac{\bar{X}_T-\bar{X}_{NT}}{\sqrt{S^2_T+S^2_{NT}}}\]</span></p>
<p>También vale la pena no perder de vista la razón de varianzas (VR). Se espera que este ratio no sea muy distinto de 1 después de hacer el emparejamiento:</p>
<p><span class="math display">\[VR=\frac{S^2_T}{S^2_{NT}}\]</span></p>
<p>Como regla de dedo, una diferencia de 0.1 o menos en el SMD se considera un buen balance. Por ejemplo, la escolaridad de la madre tenía un SDM de -0.5955 en la muestra en bruto, pero con el emparejamiento el SDM se vuelve de solo 0.0171.</p>
</div>
<div id="loveplot" class="section level2">
<h2><em>Loveplot</em></h2>
<p>Usando la librería <em>cobalt</em> podemos construir un <em>love plot</em> que representa gráficamente las diferencias antes y después del emparejamiento</p>
<pre class="r"><code>love.plot(bal.tab(m.out),
          threshold = .1)</code></pre>
<p><img src="/notas/emparejamiento_en_R_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="efecto-de-tratamiento" class="section level2">
<h2>Efecto de tratamiento</h2>
<p>Existen muchas maneras de explotar la muestra emparejada. Aquí veremos la más sencilla. Simplemente consideremos a la muestra emparejada como si viniera de un experimento. Sin embargo, debemos poner especial atención a la forma de hacer inferencia pues no debemos ignorar que el PS es estimado.</p>
<p>Dependiendo de si el emparejamiento ocurre con o sin reemplazo, y de la naturaleza de la variable dependiente, se recomiendan distintas maneras de estimar el efecto del tratamiento y hacer inferencia. Una buena guía está en la documentación de <a href="https://kosukeimai.github.io/MatchIt/articles/estimating-effects.html">MatchIt</a>.</p>
<p>Por ejemplo, cuando se realiza el emparejamiento sin reemplazo, <a href="https://www.tandfonline.com/doi/full/10.1080/01621459.2020.1840383?casa_token=7VdQFPydVtIAAAAA%3A3VRshT4TmqjnyzS2Nz2EBmFi54NlHDIWdtD-mDdAdPHuv51BhbXh1qYOwsRo8yH_WhA1UoUbvP0Kqg">Abadie &amp; Spiess (2019)</a> muestran que podemos estimar los errores estándar simplemente agrupando a nivel de pareja (o grupo) emparejado (<strong>subclass</strong> es una columna que enumera a las parejas o grupos emparejados y es construida automáticamente por <em>matchit</em>).</p>
<pre class="r"><code>tt1 &lt;- lm(bweight ~ smoke,
          data = m.data,
          weights = weights)

#Errores agrupados a nivel subclass
coeftest(tt1,
         vcov. = vcovCL,
         cluster = ~subclass)</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error  t value  Pr(&gt;|t|)    
## (Intercept) 3332.054     21.585 154.3697 &lt; 2.2e-16 ***
## smoke       -194.395     28.431  -6.8373 1.116e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Algunos autores incluyen los covariables en su estimación:</p>
<pre class="r"><code>tt2 &lt;- lm(bweight ~ smoke + married + firstbaby + medu + nprenatal + foreign + mhisp + fage,
          data = m.data,
          weights = weights)

#Errores agrupados a nivel subclass
coeftest(tt2,
         vcov. = vcovCL,
         cluster = ~subclass)</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##               Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept) 2956.12820   75.62858 39.0874 &lt; 2.2e-16 ***
## smoke       -195.89513   28.27493 -6.9282 6.003e-12 ***
## married      107.92923   30.43543  3.5462 0.0004013 ***
## firstbaby    -54.86645   29.63670 -1.8513 0.0642977 .  
## medu           1.70500    5.37644  0.3171 0.7511879    
## nprenatal     32.45314    4.46216  7.2730 5.319e-13 ***
## foreign        9.34224  107.13207  0.0872 0.9305203    
## mhisp        120.09494   84.84348  1.4155 0.1571066    
## fage           0.14779    1.43275  0.1032 0.9178528    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Cuando el emparejamiento es con reemplazo, las unidades no tratadas son emparejadas varias veces (aparecen repetidas en la muestra emparejada), lo cual debe ser considerado para estimar los efectos del tratamiento y hacer inferencia. Por ejemplo, se puede usar <em>bootstrap</em> para obtener el error estándar del efecto del tratamiento cuando la variable de impacto es continua.</p>
</div>
<div id="conclusión" class="section level2">
<h2>Conclusión</h2>
<p>Las técnicas basadas en el PS no son usadas extensivamente en economía para hacer inferencia directamente. El PSM es usado más en disciplinas como la bioestadística, para corregir posibles desbalances en las muestras.</p>
<p>Actualmente, el PS ha tomado relevancia como herramienta auxiliar, por ejemplo, para los métodos doblemente robustos, para agregar comparaciones de diferencia en diferencias con adopción escalonada, y en métodos de aprendizaje computacional</p>
</div>
